#config_version=6
# lowerlanes config file
#



                # To re-activate the left Out-Lane Kicker light all 3 Radiation
                  # Target Lights.
                # To re-activate the right Out-Lane kicker light all 3 Comet
                  # Target Lights.

      # Bonus Lane
        # - Single lane between the Left Out-Lane and the Left Return Lane.
        # - The Bonus Lane is always passed when the Ball passes the Launch Ramp.
        # - Enter this lane to "Re-fuel' the ship.
        # - Extra points are awarded if the Bonus Lane Light is on and the Bonus was activated
                # * Lane Pass - 10,000 points
                # * See the Bonus Section for more information.
      
      # Out-Lanes
        # - 2 Lanes located at the lower-left and lower-right of the Table.
        # - Pass this lane and the ball drains or enters the Out-Lane Kicker when the kicker is activated.
                # * Lane Pass - 20,000 points.
                # * Extra Ball Light - 20,000 points + Extra Ball is awarded.
      
      # LANE LIGHTS
        # Bonus Lane
        # - Single light in the Bonus Lane.
        # - Indicates a bonus is available in this lane.
        # - Activated when a mission is completed.
        # - Goes out when the Ball passes the Bonus Lane.
        
        # Out Lanes
        # - Single light located at the top of each of the Out-Lanes (2 lights total).
        # - Indicates an Extra Ball is available in this lane.
        # - Pass the lane to receive an Extra Ball.
        
mode:
  start_events: ball_started
  stop_events: ball_stopped
  priority: 200

shots:
  bonusLane_shot:
    switch: s_bonus_lane
  outLaneL_shot:
    switch: s_left_out_lane
    profile: outLane
  outLaneR_shot:
    switch: s_right_out_lane
    profile: outLane

shot_groups:
    outLane_shot:
        shots: outLaneL_shot, outLaneR_shot
           
shot_profiles:
  outLane:
    states:
      - name: unlit
        show: off

variable_player:
  outLane_shot_unlit_hit:
    score: 20000

sound_player:
 #   reentry_sound_active:
     s_bonus_lane_active:
        reentry_sound:
            action: play
     s_left_out_lane_active:
        reentry_sound:
            action: play
     s_right_out_lane_active:
        reentry_sound:
            action: play

shows: 
