#config_version=6
# mode2 config file

mode:
  start_events: mode2_start #, device.shots.my_first_shot_mode2.state:0
  stop_events: mode2_stop
  priority: 200

widgets:
  mode2_start_banner:
    type: text
    text: MODE 2 STARTED
    font_size: 50
    color: lime
    y: 80%
    expire: 1s

widget_player:
  mode_mode2_started: mode2_start_banner

variable_player:
  my_first_shot_mode2_flashing_hit:
    score: 10000
  my_first_shot_mode2_lit_hit:
    score: 100

shots:
  my_first_shot_mode2:
    switch: s_reentry_left
    show_tokens:
      led: l_re-entry_left
    profile: mode2
    restart_events: mode2_start

shot_profiles:
  mode2:
    states:
      - name: flashing
        show: flash
        speed: 5
      - name: lit
        show: on
    loop: true
    block: true

# event_player:
  # mode_mode2_start:
    # device.shots.my_first_shot_mode2.state_name='flashing'    